orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-pushh-image:
          account-url: "543820583940.dkr.ecr.us-east-1.amazonaws.com"
          aws-access-key-id: "AKIAX5HR3SQCLSMBCGNW"
          aws-secret-access-key: "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"
          context: myContext
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          profile-name: myProfileName
          region: "us-east-1"
          repo: "myECRRepository"
          skip-when-tags-exist: false
          tag: 'latest,myECRRepoTag'
