orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: env_url
          aws-access-key-id: env_access
          aws-secret-access-key: ${env_secret}
          context: myContext
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          profile-name: myProfileName
          region: ${env_region}
          repo: "myECRRepository"
          skip-when-tags-exist: false
          tag: 'latest,myECRRepoTag'
